-- group: The trap
-- title: jobs[].invoice_number and invoices[].invoice_number stay disagreeing
--
-- THIS ASSERTION LOCKS IN A DEFECT ON PURPOSE. Read it before "fixing" data.
--
-- The export contains TWO DIFFERENT NUMBERING SYSTEMS that share one field
-- name. jobs[].invoice_number is the reference office staff say out loud;
-- invoices[].invoice_number is the billing document's own number. They are
-- unrelated sequences, each internally unique, and they DO NOT agree:
--
--   * on 1,695 of 1,700 invoice-to-job joins (99.7%) the two numbers differ,
--     with 508 distinct deltas — it is not an offset, it is not derivable
--   * 1,687 of 1,700 invoice numbers (99.2%) are ALSO a valid job number,
--     pointing at a COMPLETELY DIFFERENT job
--   * exactly 5 invoices agree with their job by coincidence
--
--     job_7f2d1022...  job.invoice_number     = "3695"
--     invoices["3695"].job_id                 = job_dd4866de...   <- a different job
--
-- A caller saying "I'm calling about 3695" therefore has an ~84% chance of
-- reaching the wrong customer's job if the lookup hits the wrong table. Task 5
-- namespaces them apart as job_ref and invoice_ref, and nothing downstream is
-- permitted to compare the two.
--
-- WHY THIS IS AN ASSERTION AND NOT A COMMENT: a comment can be read, agreed
-- with, and then quietly undone. If someone later "repairs" the export by
-- aligning the two numbering systems, every join, every namespaced ref and
-- every disambiguation rule built on the distinction becomes wrong — and
-- nothing else in this suite would notice, because aligned numbers look
-- HEALTHIER than misaligned ones. The agreement count is therefore pinned to
-- exactly 5. Five is not a target; it is a fingerprint of this export.
--
-- If this fails, do not adjust the number. Find out who changed the data.
-- Measured: 5 of 1,700.

with jobs as (
  select payload ->> 'id'             as job_id,
         payload ->> 'invoice_number' as job_invoice_number
  from raw_record
  where file = 'jobs.jsonl'
),
invoices as (
  select payload ->> 'id'             as invoice_id,
         payload ->> 'job_id'         as job_id,
         payload ->> 'invoice_number' as invoice_invoice_number
  from raw_record
  where file = 'invoices.jsonl'
),
joined as (
  select i.invoice_id,
         i.job_id,
         i.invoice_invoice_number,
         j.job_invoice_number
  from invoices i
  join jobs j on j.job_id = i.job_id
),
tally as (
  select count(*) filter (where invoice_invoice_number = job_invoice_number) as agreeing,
         count(*) filter (where invoice_invoice_number is distinct from job_invoice_number) as disagreeing,
         count(*) as joined_rows
  from joined
)
select
  'invoices whose invoice_number equals its job''s invoice_number' as measure,
  5           as expected,
  agreeing    as actual,
  disagreeing as disagreeing,
  joined_rows as invoice_job_joins,
  'Two numbering systems have converged or diverged. Do NOT edit this file — '
  || 'find out what changed the data. Every namespaced job_ref/invoice_ref '
  || 'lookup downstream depends on this distinction.' as what_to_do
from tally
where agreeing <> 5;
